Bot:
  TelegramToken: "TELEGRAM_BOT_TOKEN"
  ChatId: CHAT_ID
  AdminUserId: ADMIN_USER_ID

mail:
  Host: "smtp.gmail.com"
  Port: 587
  From: "MAIL_USERNAME"
  Password: "MAIL_PASSWORD"
  UsersMailDomain: [
    "niuitmo.ru",
    "edu.itmo.ru",
  ]

DB:
  ConnectionString: "CONNECTION_STRING"
  NumberOfDeadlockRepeats: 5
  DefaultTimeout: 00:05:00

Source:
  MyItmo:
    Url: "https://my.itmo.ru/api/personalities/persons"
    Bearer: "MYT_BEARER_TOKEN"
  Start: true
  EachLimit: 10000
  Groups: [
    # 1 course pattern
    P31,    
    # 2 course pattern
    P32,
    # 3 course pattern
    P33,
    # 4 course pattern
    P34,
  ]
  